---
- name: play2
  hosts: testrestconf
  gather_facts: no
  tasks:
    - name: Restconf banner
      uri:
        url: "https://[{{ ansible_host }}]/restconf/data/native/banner/motd/banner"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: PUT
        headers:
          Content-Type: 'application/yang-data+json'
          Accept: 'application/yang-data+json,application/yang-data.errors+json'
        body_format: json
        body: '{ "Cisco-IOS-XE-native:banner": "this banner was configured using ansible via restconf" }'
        validate_certs: false
        status_code: [200, 204]